apiVersion: v2
name: node-app
description: A Helm chart for deploying Node/Java application to Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/bhandhuvistu/my-testing-
maintainers:
  - name: DevOps Team
    email: devops@example.com
